@startuml CaruCation
skinparam linetype ortho
'left to right direction
skinparam nodesep 5


<style>
.System{
    BackGroundColor #ff6644
}
</style>

skinparam component {
    backgroundColor<<Component>> Yellow
}

node "Car-u-Cation" << System >> as c{
    Component "**VideoService**" <<Component>> as vs
    Component "**VideoRatingService**" <<Component>> as vrs
    Component "**AdminService**" <<Component>> as ad
    Component "**LoginService**" <<Component>> as ls
    Component "**IntranetService**" <<Component>> as is
    Component "**VideoDisplay**" <<Component>> as vd

    vs --[dotted]-> vrs: Sending Request
    ad --[dotted]-> vrs: Getting Rating data
    ad --[dotted]-> ls: Getting user data
    ad --[dotted]-> is: Sending data
    vs --[dotted]-> vd: Sending data
}

component "AdminService" <<Component>> as a {
    Component "**VideoManagement**" <<Component>>
    Component "**RatingManagement**" <<Component>>
    Component "**UserManagement**" <<Component>>
    Component "**IntranetManagement**" <<Component>>
}

component "DisplayService" <<Component>> as b {
    Component "**VideoVerwalten**" <<Component>>
    Component "**VideoSichbarkeit**" <<Component>>
    Component "**VideoRatingData**" <<Component>>
}


@enduml