@startuml Notiz

'Role 1
: <<Role>>\nUserRole1:
'Role 2
skinparam {
ActorFontName Courier
ActorBackgroundColor<< Human >> Yellow
}
UserRole2 << Human >>
'Role 3
:UserRole3:


'left to right direction
skinparam component {
    backgroundColor<<Component>> #fff2cc
    FontStyle normal
}
'anders Schreibweise
[**Meal** **Display** \n**Component**] <<Component>> as a
[===Meal Data Acquisition \n**Component**] <<Component>> as b
a --> b  #black;line.dashed;:<<use>>\n get meal info

'mit Abstand
component "**Weather**" <<Component>> as c #fff2cc{
    label "\n"
}

'Layer kann mit folder und package abgebildet werden
folder "<<layer>> \nLayer 1" as f #ffe6cc {
        node "def" << System >> as def #fff2cc

}
package "<<layer>> \nLayer 2" as p  #ffe6cc{
        node "abc" << System >> as abc #fff2cc
}

'Problem bei OP
action "Operation Process" <<Operation Process>> as op #ffe6cc
action "<<Operation Process>>" <<**Operation Process**>> as op1 #ffe6cc{
    node "**Java Virtual Machine**" <<Execution Environment>> as h1 #fff0e8{
        artifact "What2Eat Backend.jar" <<Deployment Artifact>> as l1
    }
}
@enduml