@startuml test

!define Yellow #fff2cc
!define Green #b9e0a5
!define Pink #fff0e8
!define Red #f8cecc
!define Orange #ffe6cc
!define White #ffffff

node "**System**" <<System>> as s Yellow{
    'hier kann Componente hinzugefügt werden, ansonsten '{}' weglassen.
}

@enduml