@startuml DD_Activities@Devtime
'left to right direction

skinparam  {
    node {
        FontStyle normal
        BackgroundColor #ffe6cc
    }
    artifact {
        FontStyle normal
        BackgroundColor #b9e0a5
    }
    component {
        FontStyle normal
        BackgroundColor #fff2cc
    }
    rectangle {
        FontStyle normal
        BackgroundColor #fff2cc
    }
    database {
        BackgroundColor #f8cecc
    }
    'linetype ortho
}

:Release Manager: as rm #fff2cc
:Developer: as dev #fff2cc

node "**Developer PC**" <<Computing Node>> as a #ffe6cc{
    node "**Local Test Environment**" <<Execution Environment>> as b #fff0e8{
        artifact "Platform.war" <<Deployment Artifact>> as a1
    }
    [===IDE] <<Component>> as c
    rectangle "===Code Base" <<Data>> as d
}


node "**Build Server**" <<Computing Node>> as e #ffe6cc{
    node "**Build Test Environment**" <<Execution Environment>> as f #fff0e8{
        artifact "Platform.war" <<Deployment Artifact>> as a2
    }
    [===Jenkins] <<Component>> as g
    rectangle "===Code Base" <<Data>> as h
}


node "**Dev Server**" <<Computing Node>> as i #ffe6cc{
    node "**Elastic Beanstalk**" <<Execution Environment>> as j #fff0e8{
        artifact "Platform.war" <<Deployment Artifact>> as a3
    }
}

node "**Stage Server**" <<Computing Node>> as k #ffe6cc{
    node "**Elastic Beanstalk**" <<Execution Environment>> as l #fff0e8{
        artifact "Platform.war" <<Deployment Artifact>> as a4
    }
}

node "**Production Server**" <<Computing Node>> as m #ffe6cc{
    node "**Elastic Beanstalk**" <<Execution Environment>> as n #fff0e8{
        artifact "Platform.war" <<Deployment Artifact>> as a5
    }
}

artifact "Platform.war" <<Deployment Artifact>> as a6{
    note "Config: \n-local \n-test \n-dev \n-stage \n-prod" as n1 #ffffff
}

database "Git \nRepository" as git

rm -d-> dev

rm -> e #black;line.dashed;:<<operate>> \ntrigger stage \nor prod \ndeployment
dev -> a #black;line.dashed;:<<use>>
a -> git #black;line.dashed;:push
git -> e #black;line.dashed;:notify
e -> git #black;line.dashed;:pull
e -> a6 #black;line.dashed;:create
a6 -> i #black;line.dashed;:deploy on each build
a6 -> k #black;line.dashed;:deploy on release trigger
a6 -> m #black;line.dashed;:deploy on release trigger

'position
i -[hidden]d- k
k -[hidden]d- m
e -[hidden]d- a
@enduml