@startuml DD_Activities@Devtime
!include color.plantuml

'left to right direction

skinparam  {
    node {
        FontStyle normal
        BackgroundColor Orange
    }
    artifact {
        FontStyle normal
        BackgroundColor Green
    }
    component {
        FontStyle normal
        BackgroundColor Yellow
    }
    rectangle {
        FontStyle normal
        BackgroundColor Yellow
    }
    database {
        BackgroundColor Red
    }
    'linetype ortho
}

:  <<Role>>\n**Developer**: as dev Yellow

node "**Build Server**" <<Computing Node>> as e {
    node "**Build Test Environment**" <<Execution Environment>> as f Pink{
        artifact "**Platform.war**" <<Deployment Artifact>> as a2
    }
}


node "**Dev Server**" <<Computing Node>> as i {
    node "**Elastic Beanstalk**" <<Execution Environment>> as j Pink{
        artifact "**Platform.war**" <<Deployment Artifact>> as a3
    }
}

node "**Stage Server**" <<Computing Node>> as k {
    node "**Elastic Beanstalk**" <<Execution Environment>> as l Pink{
        artifact "**Platform.war**" <<Deployment Artifact>> as a4
    }
}

artifact "**Platform.war**" <<Deployment Artifact>> as a6{
    note "Config: \n-local \n-test \n-dev \n-stage \n-prod" as n1 White
}

database "Git \nRepository" as git


dev .> git :push
git ..> e : notify
e .> git : pull
e ..> a6 : create
a6 ..> a3 :deploy on each build
a6 ..> a4 :deploy on release trigger

@enduml