@startuml define file

' Define the procedure
' !unquoted procedure $external_System($alias)
' skinparam {
'     rectangle {
'         FontStyle normal
'         BackgroundColor #fff2cc
'     }
' }
'   rectangle **$alias** <<External System>>{    
'   }
' !endprocedure

skinparam rectangle {
    FontStyle normal
}


!define System(e_alias, e_label) rectangle "**e_label**" <<System>> as e_alias #fff2cc
!define External_System(e_alias, e_label) rectangle "**e_label**" <<External System>> as e_alias #fff2cc


'Relationships
!define Rel_Use(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : <<use>>"e_label"
!define Rel_Dataflow(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : <<dataflow>>"e_label"
!define Rel_Refine(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : <<refine>>"e_label"
!define Rel_Operate(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : <<operate>>"e_label"
!define Rel_Execute(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : <<execute>>"e_label"
!define Rel_Deploy(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : <<deploy>>"e_label"
!define Rel_Own(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : <<own>>"e_label"
!define Rel_Manifest(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : <<manifest>>"e_label"
!define Rel_Agre(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : "e_label"

!define Rel_(e_sourceAlias, e_targetAlias, e_label, e_direction="") e_sourceAlias e_direction e_targetAlias : "e_label"
!define Rel_Generalization(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "-|>")
!define Rel_Realization(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "..|>")
!define Rel_Composition(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "*--")
!define Rel_Aggregation(e_From, e_To, e_label="") Rel_(e_From, e_To, e_label, "o--")

@enduml