@startuml test
!include customized-elements/withDefine.plantuml

'$external_System(Twitter)

External_System(a, PayPal)
System(b, Twitter)
System_Scope(c)
Component(d, Controller)

Rel_Use(a, c, "hello", ..>)
Rel_Manifest(a, b, "world", ..>)
Rel_Use(c, d, "test", -->)




@enduml