@startuml test
!include customized-elements/withDefine.plantuml

'$external_System(Twitter)
System_Scope(a)
System(b, Amazon)
External_System(c, PayPal)
Component(d, Service)
Component(e, Controller)
Rel_(a, b, "<<include>>", ..>)
Rel_Connector(b, c,"use")
Rel_(b, d, "<<include>>", ..>)
Rel_(b, e, "<<include>>", ..>)
Rel_Use(e, d,, .>)





@enduml