@startuml !Procedure

!procedure $msg($source, $destination)
  $source .l> $destination :<<dataflow>>
!endprocedure

!procedure $external_system($alias)
skinparam {
    rectangle {
        FontStyle normal
        BackgroundColor #fff2cc
    }
 }
!if ($external_system != "")
    !$sysTags = $external_system
!else
    !$sysTags = 'External System'
!endif

rectangle **$alias** <<External System>> as b{

}
!endprocedure

!procedure $System($alias, $component="", $component1="")
  skinparam {
      rectangle {
          FontStyle normal
          BackgroundColor #fff2cc
      }
  }

  !if ($component != "")
    !$compTag = $component
  !else
    !$compTag = 'Component'
  !endif

  !if ($component1 != "")
    !$compTag1 = $component1
  !else
    !$compTag1 = 'component1'
  !endif
  rectangle **$alias** <<System>> as a{
      $addComponent($compTag)
      $addComponent($compTag1)
  }
!endprocedure


!procedure $addComponent($alias)
  rectangle **$alias** <<Component>>{
  }
!endprocedure


$System(Test, AuthService, UserService)
$external_system(Firebase)
$msg(b,a)

'Das ist für Class Diagram
' !procedure $init_class($name)
'   class $name {
'     $addCommonMethod()
'   }
' !endprocedure

' !procedure $addCommonMethod()
'   toString()
'   hashCode()
' !endprocedure

' $init_class("foo1")
' $init_class("foo2")
' $msg("foo1", "foo2")

@enduml