@startuml system context
!include color.plantuml

:Student: as s Yellow
rectangle "System Scope" as SystemScope #line.dashed{
    node "What2Eat" << System >> as e Yellow
}
node "Weather Service" << External System >> as w Yellow
node "Cafeteria Menu Service" << External System >> as c Yellow

s ..> e  :<<use>> \n Get meal of the day with coldbowl info 
e -(0- w: use
e -(0- c: use

@endulm