@startuml solution approach
!include color.plantuml
'left to right direction
skinparam component {
    backgroundColor Yellow
    FontStyle normal
}

[**Meal** **Display** \n**Component**] <<Component>> as a
[===Meal Data Acquisition \n**Component**] <<Component>> as b

a .> b  :<<use>>\n get meal info
@enduml