@startuml solution approach
left to right direction
skinparam component {
    backgroundColor<<Component>> #fff2cc
    FontStyle normal
}

[**Meal** **Display** \n**Component**] <<Component>> as a
[===Meal Data Acquisition \n**Component**] <<Component>> as b

a --> b  #black;line.dashed;:<<use>>\n get meal info
@enduml