@startuml system structure
!include color.plantuml
left to right direction
skinparam{
    'linetype ortho
    component {
    backgroundColor Yellow
    FontStyle normal
    }
}

'** für Bold
Component "**Meal Display** \n**Component**" <<Component>> as a
Component "**MealService**" <<Component>> as b
Component "**WeatherService**" <<Component>> as c
Component "**MenuService**" <<Component>> as d

a ..> b  :<<dataflow>>\n MealQuery
a <.. b  :<<dataflow>>\n ExtendedMeal

b ..> c  :<<dataflow>>\n WeatherRequest
b <.. c  :<<dataflow>>\n WeatherResponse

b ..> d  :<<dataflow>>\n MealQuery
b <.. d  :<<dataflow>>\n BasicMeal

note "Calculate cold bowl probability." as n White
n .l. b 

@enduml