@startuml data model
!include color.plantuml

skinparam rectangle {
    BackgroundColor Yellow
    FontStyle normal
}

rectangle "**MealQuery**" <<Data>> as a {
    label "date"
}

rectangle "**ExtendedMeal**" <<Data>> as b {
    label "date \nmeal \nprice \ncoldBowlProbability"
}

rectangle "**BasicMeal**" <<Data>> as c {
    label "date \nmeal \nprice"
}

rectangle "**WeatherRequest**" <<Data>> as d {
    label "city \ncdateAndTime"
}

rectangle "**WeatherResponse**" <<Data>> as e {
    label "temperatureInCelsius"
}

@enduml