@startuml code organization Devtime
!include color.plantuml
left to right direction
skinparam {
   'linetype ortho
    rectangle {
    backgroundColor<<Module>><<Library>> Green
    FontStyle normal
    }
}


rectangle "**MealController**" <<Module>> as a
rectangle "**MealService**" <<Module>> as b
rectangle "**WeatherBitService**" <<Module>> as c 
rectangle "**MensaKIService**" <<Module>> as d
rectangle "**Jackson**" <<Library>> as e
rectangle "**OkHttp**" <<Library>> as f

a ..> b  :<<use>>\n getExtendedMeal
a ..> e  :<<use>>

b ..> c  :<<use>>\n getTemperature
b ..> d  :<<use>>\n getBasicMeal

c ..> e  :<<use>>
c ..> f  :<<use>>

d ..> e  :<<use>>
d ..> f  :<<use>>

@enduml