@startuml code organization Devtime
left to right direction
skinparam rectangle {
    backgroundColor<<Module>><<Library>> #b9e0a5
    FontStyle normal
}


rectangle "**MealController**" <<Module>> as a
rectangle "**MealService**" <<Module>> as b
rectangle "**WeatherBitService**" <<Module>> as c 
rectangle "**MensaKIService**" <<Module>> as d
rectangle "**Jackson**" <<Library>> as e
rectangle "**OkHttp**" <<Library>> as f

a --> b  #black;line.dashed;:<<use>>\n getExtendedMeal
a --> e  #black;line.dashed;:<<use>>

b --> c  #black;line.dashed;:<<use>>\n getTemperature
b --> d  #black;line.dashed;:<<use>>\n getBasicMeal

c --> e  #black;line.dashed;:<<use>>
c --> f  #black;line.dashed;:<<use>>

d --> e  #black;line.dashed;:<<use>>
d --> f  #black;line.dashed;:<<use>>

@enduml