@startuml code organization Runtime
!include color.plantuml
left to right direction
skinparam component {
    backgroundColor Yellow
    FontStyle normal
}

Component "**MealController**" <<Component>> as a
Component "**MealService**" <<Component>> as b
Component "**WeatherBitService**" <<Component>> as c
Component "**MenuService**" <<Component>> as d

a ..> b  :<<use>>\n getExtendedMeal
b ..> c  :<<use>>\n getTemperature
b ..> d  :<<use>>\n getBasicMeal
@enduml