@startuml deployment server
!include color.plantuml

'left to right direction
skinparam  {
    node {
        FontStyle normal
        BackgroundColor Orange
    }
    artifact {
        FontStyle normal
        BackgroundColor Green
    }
    linetype ortho
}

node "**Mobile Device**" <<Computing Node>> as a {
    node "**OS App-Sandbox**" <<Execution Environment>> as e Pink{
        artifact "**What2Eat Mobile App**" <<Deployment Artifact>> as i
    }
}

node "**Mobile Device**" <<Computing Node>> as b {
    node "**Web Browser**" <<Execution Environment>> as f Pink{
        artifact "**What2Eat Web App**" <<Deployment Artifact>> as j
    }
}

node "**Desktop PC**" <<Computing Node>> as c {
    node "**Web Browser**" <<Execution Environment>> as g Pink{
        artifact "**What2Eat Web App**" <<Deployment Artifact>> as k
    }
}

node "**Backend Server**" <<Computing Node>> as d {
    node "**Java Virtual Machine**" <<Execution Environment>> as h Pink{
        artifact "**What2Eat Backend.jar**" <<Deployment Artifact>> as l
    }
}

e --> h :<<use>>
f --> h :<<use>>
g --> h :<<use>>

@enduml