@startuml deployment client
!include color.plantuml

left to right direction
skinparam  {
    node {
        FontStyle normal
        BackgroundColor Orange
    }
    artifact {
        FontStyle normal
        BackgroundColor Green
    }
}


node "**Student's PC**" <<Computing Node>> as a {
    node "**Local Web Browser**" <<Execution Environment>> as b Pink{
        artifact "**What2Eat Web App**" <<Deployment Artifact>>
    }
    node "**Java Virtual Machine** \n**(inside IntelliJ)**" <<Execution Environment>> as c Pink{
        artifact "**What2Eat Backend**" <<Deployment Artifact>>
    }
}

b ..> c :<<use>>
'a -( : query weather 
'nicht abbildbar

@enduml