@startuml solution idea
!include color.plantuml

'left to right direction
skinparam  {
    node {
        FontStyle normal
        BackgroundColor Yellow
    }
    rectangle {
        FontStyle normal
    }
}

rectangle "System Scope" as s #line.dashed{
    node "What2Eat" << System >> as a 
}
node "Weather Service" << External system >> as w 
node "Cafeteria Menu Service" << External system >> as c 

rectangle "**Java**" <<Technology>> as b Red
rectangle "**WeatherBit API**" <<Technology>> as d Red
rectangle "**Mensa-KI.de API**" <<Technology>> as e Red

a -(0- w: query weather
a -(0- c: query meal(s)
b ..|> a
d .u.|> w
e .u.|> c

@enduml