@startuml DocChess function devtime

!include color-code.plantuml
'left to right direction
skinparam  {
    package {
        FontStyle normal
    }
    rectangle {
        FontStyle normal
    }
    'linetype ortho
}


package "<<Package>> \nXBoard" as p1 Green {
    rectangle "**Main**" <<Module>> as m1 Green
    rectangle "**XBoard**" <<Module>> as m2 Green
}

package "<<Package>> \nEngine" as p2 Green {
    rectangle "**DefaultEngine**" <<Module>> as m3 Green
    rectangle "**Engine**" <<Interface>> as i1 Green
}

package "<<Package>> \nRegeln" as p3 Green {
    rectangle "**DefaultSpielregeln**" <<Module>> as m4 Green
    rectangle "**Spielregeln**" <<Interface>> as i2 Green
}

package "<<Package>> \nEröffnung" as p4 Green{
    rectangle "**PolyglotOpeningBook**" <<Module>> as m5 Green
    rectangle "**Eröffnungsbibliothek**" <<Interface>> as i3 Green
}

package "<<Package>> \nAllgemin" as p5 Green{
    rectangle "**Zug**" <<Module>> as m6 Green
    rectangle "**Feld**" <<Module>> as m7 Green
    rectangle "**Figur**" <<Module>> as m8 Green
    rectangle "**FigurenArt**" <<Module>> as m9 Green
    rectangle "**Stellung**" <<Module>> as m10 Green
}

m2 --> m3 #black;line.dashed;:<<ziehen>>
m2 --> m4 #black;line.dashed;:<<gueltigenZugErmitteln>>
m4 --> m3 #black;line.dashed;:<<gueltigenZugLiefern>>
m3 --> m5 #black;line.dashed;:<<zugErmitteln>>

'Package Beziehungen
p1 -> p5 #black;line.dashed;:<<use>>
p2 -> p5 #black;line.dashed;:<<use>>
p3 -> p5 #black;line.dashed;:<<use>>
p4 -> p5 #black;line.dashed;:<<use>>

'innere Beziehungen
m1 -> m2 #black;line.dashed;:<<instanziiert>>
m3 -|> i1 #black;line.dashed;
m4 -|> i2 #black;line.dashed;
m5 -|> i3 #black;line.dashed;
m6 o-- m7
m6 o-- m8
m6 o-- m9


@enduml