@startuml DocChess function devtime
!include color.plantuml

'left to right direction
skinparam  {
    package {
        BackgroundColor Green
        FontStyle normal
    }
    rectangle {
        BackgroundColor Green
        FontStyle normal
    }
    'linetype ortho
}


package "<<Package>> \n**XBoard**" as p1  {
    rectangle "**Main**" <<Module>> as m1 
    rectangle "**XBoard**" <<Module>> as m2 
}

package "<<Package>> \n**Engine**" as p2  {
    rectangle "**DefaultEngine**" <<Module>> as m3 
    rectangle "**Engine**" <<Interface>> as i1 
}

package "<<Package>> \n**Regeln**" as p3  {
    rectangle "**DefaultSpielregeln**" <<Module>> as m4 
    rectangle "**Spielregeln**" <<Interface>> as i2 
}

package "<<Package>> \n**Eröffnung**" as p4 {
    rectangle "**PolyglotOpeningBook**" <<Module>> as m5 
    rectangle "**Eröffnungsbibliothek**" <<Interface>> as i3 
}

package "<<Package>> \n**Allgemin**" as p5 {
    rectangle "**Zug**" <<Module>> as m6 
    rectangle "**Feld**" <<Module>> as m7 
    rectangle "**Figur**" <<Module>> as m8 
    rectangle "**FigurenArt**" <<Module>> as m9 
    rectangle "**Stellung**" <<Module>> as m10 
}

m2 ..> m3 :<<ziehen>>
m2 ..> m4 :<<gueltigenZugErmitteln>>
m4 ..> m3 :<<gueltigenZugLiefern>>
m3 ..> m5 :<<zugErmitteln>>

'Package Beziehungen
p1 .> p5 :<<use>>
p2 .> p5 :<<use>>
p3 .> p5 :<<use>>
p4 .> p5 :<<use>>

'innere Beziehungen
m1 .> m2 :<<instanziiert>>
m3 .|> i1 
m4 .|> i2 
m5 .|> i3
m6 o-- m7
m6 o-- m8
m6 o-- m9


@enduml