@startuml DocChess system context
!include color.plantuml
'left to right direction
skinparam  {
    node {
        BackgroundColor Yellow
        FontStyle normal
    }
    rectangle {
        FontStyle normal
    }
    'linetype ortho
}

:Menschlicher Gegner: as s Yellow
rectangle "System Scope" as SystemScope #line.dashed{
    node "docChess" << System >> as d 
}
node "XBoard Client" << External System >> as x 
node "Computergegner" << External System >> as c 
node "Polyglot Opening Book" << External System >> as p 
node "Eröffnungen" << External System >> as e 
node "Endspiele" << External System >> as end 

note "entweder oder" as n White

s ..> x  :<<use>> \nzieht einen Zug
x .> d  :<<use>> \nkommuniziert
c ..> d  :<<use>> \nzieht einen Zug
d .> p  :<<use>> \nliest Buchdatei
p ..> e :<<use>> \nliest
p ..> end :<<use>> \nliest
s . n
n . c

@enduml