@startuml Typ Folder + Package
!include color.plantuml
<style>
folder {
    Fontstyle normal
    backgroundColor Yellow
    LineThickness 1
}
component {
    Fontstyle normal
    backgroundColor Yellow
}
Package {
    Fontstyle normal
    backgroundColor Green
    LineThickness 1
}
<style>

package "<<Package>> \n**Package**" Green {
    label "\n" as p
}

folder "<<Layer>> \n**Layer**" Yellow {
    label "\n"
}

folder "<<Cluster>> \n**Cluster**" Yellow {
    label "\n" as l
}
@enduml