@startuml Software@Devtime with color
!include color.plantuml

skinparam {
    component {
        Fontstyle normal
        backgroundColor Yellow
    }
}

package "<<Package>> \nPackage" Green {
    label "\n" as p
}

folder "<<Layer>> \nLayer" Yellow {
    label "\n"
}

folder "<<Cluster>> \nCluster" Yellow {
    label "\n" as l
}
@enduml