@startuml Typ rect-others
!include color.plantuml 
<style>
artifact {
    Fontstyle normal
    backgroundColor Green
}
<style>

skinparam{
    component {
        Fontstyle normal
        backgroundColor Yellow
    }
}
Component "**Component**" <<Component>>
artifact "**Deployment Artifact**" <<Deployment Artifact>>

@enduml