@startuml Typ Relation
!include color.plantuml
'left to right direction
skinparam {
    component {
        Fontstyle normal
        backgroundColor<<Component>> Yellow
    }
}

Component "**Component**" <<Component>> as c1
Component "**Component**" <<Component>> as c2
Component "**Component**" <<Component>> as c3
Component "**Component**" <<Component>> as c4

c1 .> c3 :<<use>>
c1 -|> c2 
c1 .|> c2 
c1 *-- c2 
c1 o-- c2 
c1 --> c2
c1<-[thickness=10]-> c4: Connector
c1 -0)- c4
@enduml