@startuml Environment@Devtime with color
!include color.plantuml

<style>
artifact{
    Fontstyle normal
    backgroundColor Green
}

note {
    backgroundColor White
}

action{
    Fontstyle normal
    backgroundColor Green
}
<style>

skinparam {
    node {
        Fontstyle normal
        backgroundColor<<Organizational Unit>> Orange
        backgroundColor<<Deployment Tool>> Green
    }

    rectangle {
        Fontstyle normal
        backgroundColor<<Technology>> Red
        backgroundColor<<Project Increment>> Green
    }
}

node "**Organizational Unit**" <<Organizational Unit>>
node "**Deployment Tool**" <<Deployment Tool>>

rectangle "**Project Increment**" <<Project Increment>>
rectangle "**Technology**" <<Technology>>

artifact "**Deployment Artifact**" <<Deployment Artifact>> 
action "**Deployment Process**" <<Deployment Process>> 

'as n zu schreiben ist erforderlich, sonst führt zu einem Fehler
note "This note is a note." as n

'Ausnahmen, die Farbe muss hinter folgende Elemente geschrieben werden
:<<Role>>\n**Role**: Yellow
@enduml