@startuml Environment@Runtime with color
!include color.plantuml

<style>
artifact{
    Fontstyle normal
    backgroundColor Green
}

note {
    backgroundColor White
}

action{
    Fontstyle normal
    backgroundColor Orange
}
<style>

skinparam {
    node {
        Fontstyle normal
        backgroundColor<<Computing Node>> Orange
        backgroundColor<<Execution Environment>> Orange
        backgroundColor<<Organizational Unit>> Orange
    }

    rectangle {
        Fontstyle normal
        backgroundColor<<Technology>> Red
        backgroundColor<<Thread>> Orange
    }
}


node "**Computing Node**" <<Computing Node>>
node "**Execution Environment**" <<Execution Environment>>
node "**Organizational Unit**" <<Organizational Unit>>

rectangle "**Technology**" <<Technology>>
rectangle "**Thread**" <<Thread>>

artifact "**Deployment Artifact**" <<Deployment Artifact>>
action "**Operation Process**" <<Operation Process>>

'as n zu schreiben ist erforderlich, sonst führt zu einem Fehler
note "This note is a note." as n

'Ausnahmen, die Farbe muss hinter folgende Elemente geschrieben werden
:<<Role>>\n**Role**: Yellow
@enduml