@startuml Element with colors
!include color.plantuml

skinparam {
    component {
        Fontstyle normal
        backgroundColor Yellow
    }

    node {
        Fontstyle normal
        backgroundColor<<System>> Yellow
        backgroundColor<<External System>> Yellow
    }

    note {
        backgroundColor White
    }

    rectangle {
        Fontstyle normal
        backgroundColor<<Technology>> Red
        backgroundColor<<Interface>> Orange
        backgroundColor<<Data>> Yellow
    }
}
node "**System**" <<System>>
node "**External System**" <<External System>>


rectangle "**Technology**" <<Technology>>
rectangle "**Interface**" <<Interface>>
rectangle "**Data**" <<Data>>

[===Component] <<Component>>

'as n zu schreiben ist erforderlich, sonst führt zu einem Fehler
note "This note is a note." as n

'Ausnahmen, die Farbe muss hinter folgende Elemente geschrieben werden 
:<<Role>>\n**Role**: Yellow

folder "<<Layer>> \nLayer" Yellow {
    [===Component] <<Component>> as c1
}

folder "<<Cluster>> \nCluster" Yellow {
    [===Component] <<Component>> as c2
}

@enduml