@startuml Software@Devtime with color
!include color.plantuml

<style>
Package {
    Fontstyle normal
    backgroundColor Green
}
note {
        backgroundColor White
}
<style>

skinparam {
    rectangle {
        backgroundColor<<Module>> Green
        backgroundColor<<Interface>> Green
        backgroundColor<<Library>> Green
        backgroundColor<<Technology>> Red
    }
}

rectangle "**Module**" <<Module>>
rectangle "**Interface**" <<Interface>>
rectangle "**Library**" <<Library>>
rectangle "**Technology**" <<Technology>>

'as n zu schreiben ist erforderlich, sonst führt zu einem Fehler
note "This note is a note." as n

package "<<Package>> \n**Package**" {
    'hier kann man Elemente hinzufügen.
    'Wenn 'as xxx' geschrieben wird, muss unbedingt ein Element in {} eingefügt werden, 
    'da sonst die Überschrift nicht mehr korrekt positioniert ist.
}

@enduml