@startuml Software@Devtime with color
!include color.plantuml
<style>
folder {
    Fontstyle normal
    backgroundColor Yellow
}

component {
    Fontstyle normal
    backgroundColor Yellow
}

note {
    backgroundColor White
}

<style>
skinparam {
    node {
        Fontstyle normal
        backgroundColor<<System>> Yellow
        backgroundColor<<External System>> Yellow
    }

    rectangle {
        Fontstyle normal
        backgroundColor<<Technology>> Red
        backgroundColor<<Interface>> Orange
        backgroundColor<<Data>> Yellow
    }
}
node "**System**" <<System>>
node "**External System**" <<External System>>


rectangle "**Technology**" <<Technology>>
rectangle "**Interface**" <<Interface>>
rectangle "**Data**" <<Data>>

[===Component] <<Component>>

folder "<<Layer>> \n**Layer**" {
    label "\n"
}

folder "<<Cluster>> \n**Cluster**" {
    label "\n" as l
}

'as n zu schreiben ist erforderlich, sonst führt zu einem Fehler
note "This note is a note." as n

'Ausnahmen, die Farbe muss hinter folgende Elemente geschrieben werden 
:<<Role>>\n**Role**:

@enduml