@startuml cluster package
!include color.plantuml
'left to right direction
skinparam component {
    backgroundColor Yellow
    FontStyle normal
}

folder "<<Cluster>> \nCluster 1" as f1 Orange{
        [===Component 1] <<Component>> as c1 
        [===Component 2] <<Component>> as c2 
        [===Component 3] <<Component>> as c3
}

folder "<<Cluster>> \nCluster 2" as f2 Orange {
        [===Component 4] <<Component>> as c4 
        [===Component 5] <<Component>> as c5 
        [===Component 6] <<Component>> as c6 
}

package "<<Package>> \nPackage 1" as p1 Green{
    label "\n" as la1
}

package "<<Package>> \nPackage 2" as p2 Green{
    label "\n" as la2
}

c1 .. c2 :<<use>>
c2 .. c3 :<<use>>
c4 .. c5 :<<use>>
c5 .. c6 :<<use>>
p1 ..|> f1  
p2 ..|> f2  

@enduml