@startuml Data-driven decomposition

skinparam rectangle {
    FontStyle normal
}

rectangle "**SomeData1**" <<Data>> as a #fff2cc{
    label "attribute1 \nattribute2 \nattribute3"
}

rectangle "**SomeData2**" <<Data>> as b #fff2cc{
   rectangle "**SomeData2a**" <<Data>> as c #fff2cc{
    label "attribute1 \nattribute2"
   }
   rectangle "**SomeData2b**" <<Data>> as d #fff2cc{
    label "attribute1 \nattribute2 \nattribute3 \nattribute4"
   }
}

rectangle "**SomeData3**" <<Data>> as e #fff2cc{
    label "\n"
}

@enduml