@startuml Data-driven decomposition
!include color.plantuml

skinparam rectangle {
    BackgroundColor Yellow
    FontStyle normal
}

rectangle "**SomeData1**" <<Data>> as a {
    label "attribute1 \nattribute2 \nattribute3"
}

rectangle "**SomeData2**" <<Data>> as b {
   rectangle "**SomeData2a**" <<Data>> as c {
    label "attribute1 \nattribute2"
   }
   rectangle "**SomeData2b**" <<Data>> as d {
    label "attribute1 \nattribute2 \nattribute3 \nattribute4"
   }
}

rectangle "**SomeData3**" <<Data>> as e {
    label "\n"
}

@enduml