@startuml Deployment-driven decomposition
!include color.plantuml
'left to right direction
skinparam  {
    node {
        FontStyle normal
        BackgroundColor Orange
    }
    artifact {
        FontStyle normal
        BackgroundColor Green
    }
    linetype ortho
}

node "**Mobile Device**" <<Computing Node>> as a {
    node "**iOS App-Sandbox**" <<Execution Environment>> as e Pink{
        artifact "**iOS Mobile App**" <<Deployment Artifact>> as i
    }
}

node "**Desktop Computer**" <<Computing Node>> as b {
    node "**Web Browser**" <<Execution Environment>> as f Pink{
        artifact "**Web App**" <<Deployment Artifact>> as j
    }
}

node "**Linux Server**" <<Computing Node>> as d #ffe6cc{
    node "**Java Virtual Machine**" <<Execution Environment>> as h Pink{
        artifact "**Server Backend.jar**" <<Deployment Artifact>> as l
    }
}

note "realize components 1, 2 and 3" as n1 White
note "realize components 4 and 5" as n2 White

'wenn Beschreibung zu lang nicht gut
e ....> h :<<use>>\nusage description
f ....> h :<<use>>\nusage description

n1 .. e 
n1 .. f 
n2 .l. h 


@enduml
