@startuml Dynamic system description
!include color.plantuml

'left to right direction
skinparam component {
    backgroundColor Yellow
    FontStyle normal
}
Component "**Component 1**" <<Component>> as c1
Component "**Component 2**" <<Component>> as c2
Component "**Component 3**" <<Component>> as c3
Component "**Component 4**" <<Component>> as c4
Component "**Component 5**" <<Component>> as c5

c ..> c1 :<<use>>\n MyRequest1
c1 ..> c3  :<<use>>\n usage 2
c2 ..> c3  :<<use>>\n usage 2
c3 ..> c4  :<<use>>\n usage 3
c2 ..> c5  :<<use>>\n usage 4
c4 ..> c5  :<<use>>\n usage 5

@enduml