@startuml layer component
'left to right direction
skinparam component {
    backgroundColor<<Component>> #fff2cc
    FontStyle normal
}

folder "<<layer>> \nLayer 1" as l1 #ffe6cc {
        [===Component 1] <<Component>> as c1
        [===Component 2] <<Component>> as c2
}

folder "<<layer>> \nLayer 2" as l2 #ffe6cc {
        [===Component 3] <<Component>> as c3
        [===Component 4] <<Component>> as c4
        [===Component 5] <<Component>> as c5
}

c1 --> c3  #black;line.dashed;:<<use>>\n usage 2
c2 --> c3  #black;line.dashed;:<<use>>\n usage 2
c3 --> c4  #black;line.dashed;:<<use>>\n usage 3
c2 --> c4  #black;line.dashed;:<<use>>\n usage 4
c4 --> c5  #black;line.dashed;:<<use>>\n usage 5

@enduml