@startuml layer package
!include color.plantuml

'left to right direction
skinparam component {
    backgroundColor Yellow
    FontStyle normal
}

folder "<<layer>> \nLayer 1" as l1 Orange {
        Component "**Component 1**" <<Component>> as c1
        Component "**Component 2**" <<Component>> as c2
}

folder "<<layer>> \nLayer 2" as l2 Orange {
        Component "**Component 3**" <<Component>> as c3
        Component "**Component 4**" <<Component>> as c4
}

folder "<<layer>> \nLayer 3" as l3 Orange {
        Component "**Component 5**" <<Component>> as c5
        Component "**Component 6**" <<Component>> as c6
}

package "<<Package>> \nPackage 1" as p1 Green{
    label "\n" as la1
}

package "<<Package>> \nPackage 2" as p2 Green{
    label "\n" as la2
}

package "<<Package>> \nPackage 3" as p3 Green{
    label "\n" as la3
}

p1 ..|> l1  
p2 ..|> l2  
p3 ..|> l3  

c1 .> c3 :<<use>>
c2 .> c4 :<<use>>
c3 .> c5 :<<use>>
c4 .> c6 :<<use>>

@enduml