@startuml layer component 3
!include color.plantuml 
left to right direction
skinparam component {
    backgroundColor Yellow 
    FontStyle normal
}

Component "**Component 3**" <<Component>> as l1 {
        port " " as in Yellow
        [===Component 3a] <<Component>> as 3a
        [===Component 3b] <<Component>> as 3b
        [===Component 3c] <<Component>> as 3c
}
in .> 3a  :<<use>>\n usage 1, usage 2
3a ..> 3b  :<<use>>\n usage 2
3a ..> 3c  :<<use>>\n usage 2

@enduml