@startuml Mapping runtime to devtime
left to right direction
skinparam  {
    component {
        FontStyle normal
        BackgroundColor #fff2cc
    }
    rectangle {
        FontStyle normal
        BackgroundColor #b9e0a5
    }
}

'1:1
[===MyComponent] <<Component>> as c1
rectangle "**MyModule**" <<Module>> as m1
c1 <|-d- m1 #black;line.dashed;

'1:n
[===MyComponent] <<Component>> as c2
rectangle "**MyModule**" <<Module>> as m2
rectangle "**MyFramework**" <<Module>> as m3
c2 <|-d- m2 #black;line.dashed;
c2 <|-d- m3 #black;line.dashed;

'n:1
[===MyComponent1] <<Component>> as c3
[===MyComponent2] <<Component>> as c4
[===MyComponent3] <<Component>> as c5
rectangle "**MyModule**" <<Module>> as m4
c3 <|-d- m4 #black;line.dashed;
c4 <|-d- m4 #black;line.dashed;
c5 <|-d- m4 #black;line.dashed;

'n:m
[===MyComponent1] <<Component>> as c6
[===MyComponent2] <<Component>> as c7
rectangle "**MyModule**" <<Module>> as m5
rectangle "**MyFramework**" <<Module>> as m6
c6 <|-d- m5 #black;line.dashed;
c6 <|-d- m6 #black;line.dashed;
c7 <|-d- m5 #black;line.dashed;
c7 <|-d- m6 #black;line.dashed;

@enduml