@startuml system context(design)
!include color.plantuml
left to right direction

:    <<Role>>\n **My Role 1**: as r1 Yellow
:    <<Role>>\n **My Role 2**: as r2 Yellow
:    <<Role>>\n **My Role 3**: as r3 Yellow

rectangle "System Scope" as SystemScope #line.dashed{
    node "**My System A**" << System >> as a Yellow
    node "**My System B**" << System >> as b Yellow
}

node "**External system 1**" << External system >> as ex1 Yellow
node "E**xternal system 2**" << External system >> as ex2 Yellow

r1 ..> a  :<<use>> \n my usage 1
r2 ..> a  :<<use>> \n my usage 2
r2 ..> b  :<<use>> \n my usage 3
r3 ..> b  :<<use>> \n my usage 4

a .> b  :<<use>> \n usage description

a -(0- ex1: interface description
b -(0- ex1: interface description
b -0)- ex2: interface description

@enduml