@startuml DokChess structure
!include color.plantuml

'left to right direction
skinparam {
    node {
        BackgroundColor Yellow
        FontStyle normal
    }
    component {
        BackgroundColor Yellow
        FontStyle normal
    }
}

node "===docChess" << System >> as d {
    [===Xboard-Protokol] <<Component>> as xp 
    [===Spielregeln] <<Component>> as sr 
    [===Engine] <<Component>> as en 
    [===Eröffnungen] <<Component>> as er 
}
node "===XBoard Client" << External System >> as x 
node "===Polyglot Opening Book" << External System >> as p 

'kann auch ohne r angezeigt werden, die Hierachie ist klarer
xp ..> en  :<<use>> \n ziehen
xp .r.> sr  :<<use>> \n ermittleGueltigenZug
sr ..> en  :<<use>> \n liefereGueltigenZug
en -r.> er  :<<use>> \n liefereErstenZug
x -(0- xp: Ein/Ausgabe
er -0)- p: leseDatei

@enduml